[package]
name = "rust-nostr-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.21.0"
futures-util = "0.3.30"
log = "0.4.21"
env_logger = "0.11.3"
nostr = "0.28.1"
